name: PlayerJoinNotify
main: com.dbkynd.PlayerJoinNotify.PlayerJoinNotify
version: '${project.version}'
author: DBKynd
command:
  pjnotify:
    description: Send an email when a player joins the server.
    usage: /<command>